using AutoMapper;
using QuanApi.Data; // Your NhanVien entity
using QuanApi.Dtos; // Your DTOs

namespace QuanApi.MappingProfiles
{
    public class NhanVienProfile : Profile
    {
        public NhanVienProfile()
        {
            // Map from NhanVienCreateDto to NhanVien entity
            CreateMap<NhanVienCreateDto, NhanVien>()
                .ForMember(dest => dest.IDNhanVien, opt => opt.Ignore()) // ID will be generated by API
                .ForMember(dest => dest.NgayTao, opt => opt.Ignore()) // Set by API
                .ForMember(dest => dest.NguoiTao, opt => opt.Ignore()) // Set by API
                .ForMember(dest => dest.LanCapNhatCuoi, opt => opt.Ignore()) // Set by API
                .ForMember(dest => dest.NguoiCapNhat, opt => opt.Ignore()) // Set by API
                .ForMember(dest => dest.TrangThai, opt => opt.Ignore()); // Set by API to default true

            // Map from NhanVienUpdateDto to NhanVien entity
            CreateMap<NhanVienUpdateDto, NhanVien>()
                .ForMember(dest => dest.IDNhanVien, opt => opt.Ignore()) // ID is from URL, not DTO
                .ForMember(dest => dest.NgayTao, opt => opt.Ignore()) // Preserve original creation date
                .ForMember(dest => dest.NguoiTao, opt => opt.Ignore()) // Preserve original creator
                .ForMember(dest => dest.LanCapNhatCuoi, opt => opt.Ignore()) // Set by API
                .ForMember(dest => dest.NguoiCapNhat, opt => opt.Ignore()); // Set by API

            // Map from NhanVien entity to NhanVienResponseDto
            CreateMap<NhanVien, NhanVienResponseDto>()
                .ForMember(dest => dest.TenVaiTro, opt => opt.MapFrom(src => src.VaiTro.TenVaiTro)); // Map TenVaiTro from VaiTro navigation property
        }
    }
}
